### ISSUE TITLE
Add documentation around deploying to AWS 

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/autonity-docs#18]
The documentation should reflect deploying to AWS using [autonity-helm][1] and [autonity-terraform][2]. This should walk the user through setting up the infrastructure using terraform and then a helm deployment. The owner of both of these projects is @eastata 

[1]: https://github.com/clearmatics/autonity-helm
[2]: https://github.com/clearmatics/autonity-terraform

**Comment by eastata** [comment]
- `autonity-helm` is ready
- `autonity-terraform` not started, move it to separated task

**Comment by shapeshed** [comment]
Could you reference the separate task please and I'll close this one.
