### ISSUE TITLE
Refactor Getting Started section

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/autonity-docs#19]
There are now three ways that people can experiment with an Autonity network

* Using `docker-compose`
* Using `helm` and `minikube` (autonity-helm)
* Using AWS (autonity-terraform & autonity-helm)

A getting started section should be expanded to include these.

**Comment by eastata** [comment]
```
Autonity Hello World
 |- (steps with links to docker-compose and api)
Autonity API
 |- ??
Network Permissioning
 |- Soma - Validator Governance
 |- Glienicke - P2P Permissioning
Istanbul Byzantine Fault Tolerance (IBFT)
 |- Consensus State Transitions
Deploy
 |- docker-compose
   |- Easy start with docker-compose
 |- Kubernetes
   |- Easy start with local kubernetes Minkube
   |- Cloud setup to Amazon EKS
   |- Cloud setup to GKE
   |- Helm chart
     |- install
     |- configure
     |- subcharts:
       |- Autonity
       |- Metrics with Prometheus & Grafana
       |- Ethstats
       |- Blockscout
       |- Dapp Validators
       |- Dapp Observers
```

**Comment by shapeshed** [comment]
We need to add a page on using DApps (validator / observer) using local or kubernetes install. We also need to understand how prefunded accounts work (if there are any) so people can deploy contracts. Finally we should walk through how to deploy the asset-token contract onto the chain, complete a funding/defunding transaction and a simple payment. It is a little early to document the API yet so leaving this out. 

How about

```
Autonity Hello World
 |- (steps with links to docker-compose and api)
Network Permissioning
 |- Soma - Validator Governance
   |- Design Goals
   |- Implementation Details
   |- Managing Validators via a DApp
 |- Glienicke - P2P Permissioning
   |- Design Goals
   |- Implementation Details
   |- Managing Validators via a DApp
Istanbul Byzantine Fault Tolerance (IBFT)
 |- Consensus State Transitions
Asset Token Contract
 |- Design Goals
 |- Implementation Details
 |- Deployment
 |- Making A Payment
Deploy
 |- docker-compose
   |- Easy start with docker-compose
 |- Kubernetes
   |- Easy start with local kubernetes Minkube
   |- Cloud setup to Amazon EKS
   |- Cloud setup to GKE
   |- Helm chart
     |- install
     |- configure
     |- subcharts:
       |- Autonity
       |- Metrics with Prometheus & Grafana
       |- Ethstats
       |- Blockscout
       |- Dapp Validators
       |- Dapp Observers
```

**Comment by shapeshed** [comment]
@flofrie @aiman :point_up:

**Comment by eastata** [comment]
I have take validators keys as a prefunded accounts.

By the first step we can describe current mechanism:
- how to get from secret addresses and private keys of validators (this accounts has prefunded)
- how to get RPC end-point
- how to connect, for example, using metamask

By the second step we can add custom options for custom definition

**Comment by shapeshed** [comment]
Sounds good. We will likely use truffle to deploy the contract and the asset token contract has no DApp.
