### ISSUE TITLE
Add documentation about using DApps

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/autonity-docs#20]
More documentation is required around using the DApps. From @flofrie:

> "As a user with an Autonity testnet, I can add or remove validators and observers to my Testnet via a UI (Dapp)".

This should satisfy the following questions for @flofrie 

* How can I launch the DApp locally or via Docker?
* How do you configure MetaMask?
* How is the contract managed (e.g. how is the private key for the contract owner defined)
* How can a user see that validators/observers have been successfully added and removed?

Information on test networks here https://github.com/clearmatics/autonity/wiki/Test-networks. The DevOps team (slack #chatops) will be able to support on configuration endpoints.

**Comment by shapeshed** [comment]
@flofrie here's the level of documentation on the DApps https://github.com/clearmatics/validator-dapp

Please could you feedback if this satisfies your requirements. We will move this into the main autonity documents. @therealdannzor is assigned to this task.

**Comment by therealdannzor** [comment]
Questions to investigate, after meeting with @flofrie about documentation today:

1. a) Documentation of (Kubernetes) Helm scripts to create a new network
    b) How to deploy the Soma and Glin contract manually - without Docker
    c) How to deploy (e.g.) the USC token and setup the monitoring scripts

2. a) What the prerequisites and requirements are to run the DApps
    b) A sequential step-by-step guide to be able to run the DApps

3.  Finally, this should, in a clear and instructional way, be explained on the Autonity docs in a coherent 
     way - from initial setup of the network to interaction with the DApps

**Comment by shapeshed** [comment]
Thanks @therealdannzor. Let's try and encourage collaboration around Github issues as there is some duplication here.

1. a) is covered and tracked in #17 and #18
    b) these are predeployed as part of the client so nothing to do
    c) this is covered and tracked in #22
2  a) and b) does apply to this ticket so please amend the issue if this is not captured
3  This is part of continually improving this documentation. We have a proposal for an improved structure here https://github.com/clearmatics/autonity-docs/issues/19#issuecomment-486226780. Feedback / contributions welcome.

**Comment by shapeshed** [comment]
closed by #27
